# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Samy\Desktop\LicencePlateId\LicencePlate-Identification\Warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 117)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Samy\\Desktop\\LicencePlateId\\LicencePlate-Identification\\../../../../../../../../Desktop/LicencePlateId/LicencePlate-Identification/Interface/Background.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 431, 41))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Pour Fermer le retour caméra appuiyez sur Q\n"
"Pour prendre une capture d\'image appuiyez sur V"))
